# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║                        🚨 CRITICAL WARNING 🚨                                ║
# ║                     AUTOGENERATED! DO NOT EDIT!                              ║
# ║                                                                               ║
# ║  This file is AUTOMATICALLY GENERATED from source modules.                   ║
# ║  ANY CHANGES MADE HERE WILL BE LOST when modules are re-exported!            ║
# ║                                                                               ║
# ║  ✅ TO EDIT: data/src/XX_platform/XX_platform.py                    ║
# ║  ✅ TO EXPORT: Run 'tren module complete XX'                                 ║
# ║                                                                               ║
# ║  🛡️ STUDENT PROTECTION: This file contains optimized implementations.        ║
# ║     Editing it directly may break module functionality and training.         ║
# ║                                                                               ║
# ║  🎓 LEARNING TIP: Work in src/ (developers) or data/modules/ (learners)      ║
# ║     The trentorch/ directory is generated code - edit source files instead!  ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝
"""
TrenTorch Platform Detection.

This file has no src/ source module (nothing under src/ defines
PlatformDetector or setup_platform_runtime, and it isn't in
export_utils.py's SOURCE_MAPPINGS), despite once carrying an
AUTOGENERATED banner claiming otherwise: it's hand-maintained
directly, here.

Distinguishes only the two runtime targets this fork actually
supports: a Jupyter kernel (the %tren magic's home, see
tren/jupyter_magic.py) and a standard CLI/script invocation. Colab,
Kaggle, and third-party judge-sandbox detection (DeepML/LeetCode/
LeetGPU), along with the import hook that let trentorch.modules.* load
directly from raw src/ files for those sandboxes, were removed
2026-08-23: this fork only ships a CLI-first, local-Jupyter workflow,
not a multi-cloud one, and none of that had a single caller left once
traced.
"""

class PlatformDetector:
    """Detects the active runtime platform."""

    @staticmethod
    def get_platform() -> str:
        """
        Returns one of:
        - 'jupyter': Jupyter Notebook / JupyterLab / IPython
        - 'standard': Standard Python script / CLI execution
        """
        try:
            get_ipython()  # type: ignore # noqa: F821
            return "jupyter"
        except NameError:
            return "standard"

    @classmethod
    def is_interactive(cls) -> bool:
        return cls.get_platform() == "jupyter"


def setup_platform_runtime() -> str:
    """Returns the detected platform. Kept as the package's init hook
    (trentorch/__init__.py calls this on import) even though it no
    longer has any side effects to set up, so that call site doesn't
    need to change if platform-specific setup is ever needed again.
    """
    return PlatformDetector.get_platform()
