"""
Developer export command: rebuilds curriculum from source files.

This is a DEVELOPER command for maintainers, NOT for students.
Workflow: data/src/*.py → data/modules/*.ipynb (stub) + data/solutions/*.ipynb
(reference) → trentorch package files, built from data/solutions/ so the
package always reflects fully-working code regardless of student progress.

Students should use `tren module complete` which only exports their own
notebook work in data/modules/ to the package (without overwriting their
notebook).
"""

import logging
from argparse import ArgumentParser, Namespace
from pathlib import Path

from rich.panel import Panel
from rich.text import Text

from platforms.cli.commands.base import BaseCommand
from platforms.cli.commands.export_utils import (
    add_autogenerated_warnings,
    convert_all_modules,
    convert_py_to_notebook,
    discover_modules,
    ensure_writable_target,
    get_export_target,
)
from platforms.cli.core.modules import get_module_name

logger = logging.getLogger(__name__)


class DevExportCommand(BaseCommand):
    """Developer export command: rebuild curriculum from src/ files."""

    @property
    def name(self) -> str:
        return "export"

    @property
    def description(self) -> str:
        return "Rebuild curriculum: data/src/*.py → data/modules/ + data/solutions/ → trentorch package files"

    def add_arguments(self, parser: ArgumentParser) -> None:
        """Add export arguments."""
        parser.add_argument("modules", nargs="*", help="Module names to export (e.g., 01 or 01_tensor)")
        parser.add_argument("--all", action="store_true", help="Export all modules")
        parser.add_argument(
            "--test-checkpoint", action="store_true", help="Run checkpoint test after successful export"
        )

    def _get_export_target(self, module_path: Path) -> str:
        return get_export_target(module_path)

    def _discover_modules(self) -> list:
        return discover_modules()

    def _add_autogenerated_warnings(self, console):
        add_autogenerated_warnings(console)

    def _convert_py_to_notebook(
        self, module_path: Path, variant: str = "stub", target_root: str = "data/modules"
    ) -> bool:
        return convert_py_to_notebook(
            module_path, self.venv_path, self.console, variant=variant, target_root=target_root
        )

    def _convert_all_modules(self, variant: str = "stub", target_root: str = "data/modules") -> list:
        return convert_all_modules(self.venv_path, self.console, variant=variant, target_root=target_root)

    def run(self, args: Namespace) -> int:
        """Handle the export command."""
        console = self.console
        logger.info("Starting dev export command")

        # Show developer warning
        console.print(
            Panel(
                "[bold yellow]⚠️  Developer Command[/bold yellow]\n\n"
                "This rebuilds notebooks from data/src/*.py files.\n"
                "[bold red]Student notebooks in data/modules/ will be OVERWRITTEN![/bold red]\n"
                "[dim]data/solutions/ (maintainer/CI reference) is also rebuilt.[/dim]\n\n"
                "[dim]Students: Use 'tren module complete' instead.[/dim]",
                title="🛠️ Developer Export",
                border_style="yellow",
            )
        )
        console.print()

        # Guard: Ensure we're in the correct directory (trentorch project root)
        # Check for key files that indicate we're in the right place
        cwd = Path.cwd()
        is_trentorch_root = (
            (cwd / "data" / "trentorch" / "__init__.py").exists()  # Running from repo root
            or (cwd / "data" / "src").exists()
            and (cwd / "pyproject.toml").exists()  # Already in trentorch/
        )
        if not is_trentorch_root:
            console.print(
                Panel(
                    "[red]❌ Must run from TrenTorch project directory[/red]\n\n"
                    "[dim]Expected structure:[/dim]\n"
                    "[dim]  <repo root>/        ← run from here[/dim]\n"
                    "[dim]  ├── data/src/[/dim]\n"
                    "[dim]  ├── data/trentorch/ ← package exports here[/dim]\n"
                    "[dim]  │   └── __init__.py[/dim]\n"
                    "[dim]  └── pyproject.toml[/dim]",
                    title="Wrong Directory",
                    border_style="red",
                )
            )
            return 1

        # Determine what to export
        if hasattr(args, "modules") and args.modules:
            return self._export_specific_modules(args.modules, console)
        elif hasattr(args, "all") and args.all:
            return self._export_all_modules(console)
        else:
            console.print(
                Panel(
                    "[red]❌ Must specify either module names or --all[/red]\n\n"
                    "[dim]Examples:[/dim]\n"
                    "[dim]  tren dev export 01[/dim]           (shorthand)\n"
                    "[dim]  tren dev export 01_tensor[/dim]    (full name)\n"
                    "[dim]  tren dev export 01 02 03[/dim]     (multiple)\n"
                    "[dim]  tren dev export --all[/dim]        (all modules)",
                    title="Missing Arguments",
                    border_style="red",
                )
            )
            return 1

    def _export_specific_modules(self, modules_to_export: list, console) -> int:
        """Export specific modules."""
        # Normalize module names (e.g., "01" -> "01_tensor", "1" -> "01_tensor")
        normalized_modules = []
        for module_input in modules_to_export:
            module_name = get_module_name(module_input)
            if module_name:
                normalized_modules.append(module_name)
            else:
                # If normalization fails, use as-is (will fail later with helpful error)
                normalized_modules.append(module_input)

        logger.info(f"Exporting specific modules: {normalized_modules}")

        console.print(
            Panel(
                f"🔄 Exporting Modules: {', '.join(normalized_modules)}",
                title="Developer Export Workflow",
                border_style="bright_cyan",
            )
        )

        solution_notebooks = []

        # Step 1: Convert each py file to both notebook variants
        for module_name in normalized_modules:
            logger.debug(f"Processing module: {module_name}")
            module_path = Path(f"data/src/{module_name}")

            if not module_path.exists():
                console.print(
                    Panel(
                        f"[red]❌ Module '{module_name}' not found in data/src/[/red]",
                        title="Module Not Found",
                        border_style="red",
                    )
                )
                self._show_available_modules(console)
                return 1

            short_name = module_name.split("_", 1)[1] if "_" in module_name else module_name
            solution_notebook = Path("data/solutions") / module_name / f"{short_name}.ipynb"

            console.print(f"📝 Converting {module_name}: data/src/*.py → data/modules/ + data/solutions/")
            if not self._convert_py_to_notebook(module_path, variant="stub", target_root="data/modules"):
                logger.error(f"Failed to convert .py to stub notebook for {module_name}")
                return 1
            if not self._convert_py_to_notebook(
                module_path, variant="solution", target_root="data/solutions"
            ):
                logger.error(f"Failed to convert .py to solution notebook for {module_name}")
                return 1
            solution_notebooks.append(str(solution_notebook))

        # Step 2: Export the solution (ground-truth) notebooks to the package
        logger.info(f"Exporting {len(solution_notebooks)} notebooks to trentorch package")
        return self._run_nbdev_export(solution_notebooks, console)

    def _export_all_modules(self, console) -> int:
        """Export all modules."""
        logger.info("Exporting all modules")

        console.print(
            Panel("🔄 Exporting All Modules", title="Developer Export Workflow", border_style="bright_cyan")
        )

        # Step 1: Convert all .py files to both notebook variants
        console.print("📝 Converting all Python files to notebooks (stub + solution)...")
        converted_stub = self._convert_all_modules(variant="stub", target_root="data/modules")
        converted_solution = self._convert_all_modules(variant="solution", target_root="data/solutions")

        if not converted_stub or not converted_solution:
            logger.error("No modules converted")
            console.print(
                Panel(
                    "[red]❌ No modules converted.[/red]\n\n"
                    "[dim]Check that:[/dim]\n"
                    "[dim]  • jupytext is installed[/dim]\n"
                    "[dim]  • data/src/*.py files exist[/dim]",
                    title="Conversion Error",
                    border_style="red",
                )
            )
            return 1

        console.print(
            f"✅ Converted {len(converted_stub)} modules to data/modules/ (stub) and {len(converted_solution)} to data/solutions/ (reference)"
        )

        # Step 2: Export all using nbdev Python API, from the solution
        # (ground-truth) notebooks -- data/trentorch/ must always reflect
        # fully-working code, independent of any student's stub progress.
        console.print("🔄 Exporting all notebooks to trentorch package (from data/solutions/)...")
        try:
            from nbdev.export import nb_export

            lib_path = Path.cwd() / "data" / "trentorch"
            nbs_path = Path.cwd() / "data" / "solutions"

            # Export all notebooks in the solutions directory
            exported_count = 0
            for nb_file in nbs_path.rglob("*.ipynb"):
                if ".ipynb_checkpoints" not in str(nb_file):
                    try:
                        nb_export(nb_file, lib_path=lib_path)
                        exported_count += 1
                    except Exception as e:
                        console.print(f"[yellow]⚠️ Skipped {nb_file.name}: {e}[/yellow]")

            if exported_count > 0:
                self._add_autogenerated_warnings(console)
                console.print(
                    Panel(
                        f"[green]✅ Successfully exported {exported_count} notebooks![/green]",
                        title="Export Success",
                        border_style="green",
                    )
                )
                return 0
            else:
                console.print(
                    Panel("[red]❌ No notebooks exported[/red]", title="Export Error", border_style="red")
                )
                return 1

        except ImportError:
            console.print(
                Panel(
                    "[red]❌ nbdev not found[/red]\n\n[dim]Install with: pip install nbdev[/dim]",
                    title="Missing Dependency",
                    border_style="red",
                )
            )
            return 1
        except Exception as e:
            console.print(
                Panel(f"[red]❌ Export failed: {e}[/red]", title="Export Error", border_style="red")
            )
            return 1

    def _run_nbdev_export(self, notebook_paths: list, console) -> int:
        """Run nbdev_export on the given notebooks using Python API directly.

        Uses nbdev.export.nb_export() directly (more reliable than subprocess).
        """
        from nbdev.export import nb_export

        success_count = 0
        lib_path = Path.cwd() / "data" / "trentorch"

        for notebook_path_str in notebook_paths:
            try:
                notebook_path = Path(notebook_path_str)
                # Ensure target file is writable
                module_path = notebook_path.parent
                export_target = self._get_export_target(module_path)
                notebook_name = notebook_path.name
                target_display = (
                    f"data/trentorch/{export_target.replace('.', '/')}.py"
                    if export_target != "unknown"
                    else "data/trentorch/..."
                )
                console.print(f"[dim]🔄 Exporting {notebook_name} → {target_display}[/dim]")

                if export_target != "unknown":
                    ensure_writable_target(export_target)

                # Use nbdev Python API directly (more reliable than subprocess)
                nb_export(notebook_path, lib_path=lib_path)
                success_count += 1
                console.print(f"✅ Exported: {notebook_name}")

            except Exception as e:
                console.print(f"❌ Error exporting {Path(notebook_path_str).name}: {e}")

        if success_count == len(notebook_paths):
            self._add_autogenerated_warnings(console)
            console.print(
                Panel(
                    f"[green]✅ Successfully exported {success_count}/{len(notebook_paths)} modules![/green]",
                    title="Export Success",
                    border_style="green",
                )
            )
            return 0
        else:
            console.print(
                Panel(
                    f"[yellow]⚠️ Exported {success_count}/{len(notebook_paths)} modules. Some failed.[/yellow]",
                    title="Partial Success",
                    border_style="yellow",
                )
            )
            return 1

    def _show_available_modules(self, console) -> None:
        """Show available modules."""
        available_modules = self._discover_modules()
        if available_modules:
            help_text = Text()
            help_text.append("Available modules:\n", style="bold yellow")
            for module in available_modules:
                help_text.append(f"  • {module}\n", style="white")
            console.print(Panel(help_text, title="Available Modules", border_style="yellow"))
