"""
MC/DC coverage for add_autogenerated_warnings' idempotent header handling:
stripping a pre-existing plain-text warning marker before re-adding the
real boxed one, and preserving a leading shebang line rather than
inserting the warning above it.
"""

from platforms.cli.commands.export_utils import add_autogenerated_warnings


class _Console:
    def print(self, *args, **kwargs):
        pass


def _run(tmp_path, monkeypatch, content):
    monkeypatch.chdir(tmp_path)
    pkg_dir = tmp_path / "data" / "trentorch"
    pkg_dir.mkdir(parents=True)
    target = pkg_dir / "thing.py"
    target.write_text(content, encoding="utf-8")
    add_autogenerated_warnings(_Console())
    return target.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# lines and "AUTOGENERATED! DO NOT EDIT! File to edit:" in lines[0]
# lines and lines[0].strip() == ""
# ---------------------------------------------------------------------------


def test_plain_marker_on_first_line_is_stripped_before_reboxing(tmp_path, monkeypatch):
    """Baseline: lines truthy, marker present on lines[0] -> that line is
    dropped before the real boxed header is inserted."""
    result = _run(tmp_path, monkeypatch, "# AUTOGENERATED! DO NOT EDIT! File to edit: x.py\nreal_code = 1\n")

    assert result.count("AUTOGENERATED! DO NOT EDIT!") == 1  # only the new boxed one
    assert "real_code = 1" in result


def test_marker_present_but_not_on_first_line_is_left_alone(tmp_path, monkeypatch):
    """lines[0] doesn't contain the marker (it's a plain code line) ->
    the strip block never fires, even though the marker text appears
    later in the file. Paired with the baseline: only which line carries
    the marker differs, isolating "in lines[0]" specifically."""
    content = "some_code = 1\n# mentions AUTOGENERATED! DO NOT EDIT! File to edit: elsewhere\n"
    result = _run(tmp_path, monkeypatch, content)

    # Both the original stray mention and the new boxed header are present
    # (nothing got silently swallowed), proving the strip block didn't touch it.
    assert result.count("AUTOGENERATED! DO NOT EDIT!") == 2


def test_blank_line_after_stripped_marker_is_also_removed(tmp_path, monkeypatch):
    """After stripping the marker line, lines[0] (now the old blank
    separator line) is itself blank -> also removed. Confirms the
    idempotency round-trips cleanly without accumulating blank lines
    across repeated runs."""
    content = "# AUTOGENERATED! DO NOT EDIT! File to edit: x.py\n\nreal_code = 1\n"
    result = _run(tmp_path, monkeypatch, content)

    lines = result.split("\n")
    # The new boxed header's own trailing content should lead straight
    # into real_code, with no leftover blank line from the old format.
    assert "real_code = 1" in lines
    real_code_index = lines.index("real_code = 1")
    assert lines[real_code_index - 1] != "" or lines[real_code_index - 1].startswith("#")


def test_no_blank_line_after_stripped_marker_is_untouched(tmp_path, monkeypatch):
    """After stripping the marker, lines[0] is real code (not blank) ->
    the second strip is skipped, nothing extra removed. Paired with the
    test above: only whether a blank separator line existed differs."""
    content = "# AUTOGENERATED! DO NOT EDIT! File to edit: x.py\nreal_code = 1\n"
    result = _run(tmp_path, monkeypatch, content)

    assert "real_code = 1" in result


# ---------------------------------------------------------------------------
# lines and lines[0].startswith("#!")
# ---------------------------------------------------------------------------


def test_shebang_line_stays_above_the_inserted_warning(tmp_path, monkeypatch):
    """Baseline: lines truthy, lines[0] starts with "#!" -> warning
    inserted at index 1, after the shebang."""
    result = _run(tmp_path, monkeypatch, "#!/usr/bin/env python3\nreal_code = 1\n")

    lines = result.split("\n")
    assert lines[0] == "#!/usr/bin/env python3"
    assert any("AUTOGENERATED! DO NOT EDIT!" in line for line in lines[1:5])


def test_no_shebang_inserts_warning_at_the_very_top(tmp_path, monkeypatch):
    """lines[0] doesn't start with "#!" -> warning inserted at index 0.
    Paired with the baseline: only the shebang's presence differs,
    isolating that condition."""
    result = _run(tmp_path, monkeypatch, "real_code = 1\n")

    lines = result.split("\n")
    assert any("AUTOGENERATED! DO NOT EDIT!" in line for line in lines[0:4])
